#server port configuration
server:
  port: 9091
#View Resolver class configuration
spring:
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp 
#datasource configuration   
  datasource: 
    type: org.apache.tomcat.dbcp.dbcp2.BasicDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
    password: manager
#hibernate property configuration
  jpa: 
   show-sql: true
